<?php

namespace AppBundle\Repository;

/**
 * BookStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
