<?php

namespace AppBundle\Repository;

/**
 * BookCompatibleStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookCompatibleStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
