<?php

namespace AppBundle\Repository;

/**
 * BookStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookStatusRepository extends \Doctrine\ORM\EntityRepository
{
    public function getOptions()
    {
        $options = [];
        foreach ($this->createQueryBuilder('c')
                     ->select('c.statusName, c.id')
                     ->getQuery()
                     ->getResult() as $item) {
            $options[$item['statusName']] = $item['id'];
        }
        return $options;
    }
}
